services:

  db:
    image: postgres:15-alpine
    container_name: converter_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: file_converter_db
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: converter_redis
    # ports:
    #   - "6379:6379"

  web:
    build: .
    container_name: converter_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: converter_worker
    user: "1000:1000"
    
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis